[fix]: fix ci.

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,28 +1,38 @@
 name: Android Build Matrix
 
-on:  push:
+on:
+  push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
 
 jobs:
+  generate-info:
+    name: Generate Class Info
+    uses: ./.github/workflows/class_info.yml
+
   build:
+    needs: generate-info
     name: ${{ matrix.name }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         include:
-          - name: "Android 32-bit"
-            arch: "armeabi-v7a"
-            build_dir_suffix: "arm32"
-            cmake_arch: "armeabi-v7a"
-            build_deps_arch: "arm"
+          # - name: "Android 32-bit"
+          #   arch: "armeabi-v7a"
+          #   build_dir_suffix: "arm32"
+          #   cmake_arch: "armeabi-v7a"
+          #   build_deps_arch: "arm"
+          #   build_ylib_arch: "aarch64"
+
+
           - name: "Android 64-bit"
             arch: "arm64-v8a"
             build_dir_suffix: "arm64"
             cmake_arch: "arm64-v8a"
             build_deps_arch: "arm64"
+            build_ylib_arch: "aarch64"
 
     steps:
     - name: Checkout yLib
@@ -32,31 +42,45 @@ jobs:
       uses: nttld/setup-ndk@v1
       id: setup-ndk
       with:
-        ndk-version: r21e
+        ndk-version: r26d
 
     - name: Setup Build Environment
       run: |
-        chmod +x build_deps.sh
-        mkdir -p build_android_${{ matrix.build_dir_suffix }}
+        mkdir -p build_android_${{ matrix.build_ylib_arch }}
 
     - name: Build Third-Party Dependencies (CMake)
       working-directory: third_part
       run: |
-        mkdir build && cd build
-        cmake .. -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_part/build/install \
+        mkdir build_android_${{ matrix.build_ylib_arch }} && cd build_android_${{ matrix.build_ylib_arch }}
+        cmake .. -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_part/build_android_${{ matrix.build_ylib_arch }}/install \
                  -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
                  -DANDROID_ABI=${{ matrix.cmake_arch }} \
+                 -DBUILD_YLIB_ARCH=${{ matrix.build_ylib_arch }} \
                  -DANDROID_PLATFORM=android-21
         cmake --build .
 
+    - name: Cache Class Info
+      id: cache-class-info
+      uses: actions/cache@v4
+      with:
+        path: docs/llvm/ylib_class_info.cpp
+        key: ylib-class-info-${{ github.sha }}
+        restore-keys: |
+          ylib-class-info-
+
     - name: Build yLib
-      working-directory: build_android_${{ matrix.build_dir_suffix }}
+      working-directory: build_android_${{ matrix.build_ylib_arch }}
       run: |
+        if [ "${{ steps.cache-class-info.outputs.cache-hit }}" != "true" ]; then
+          echo "Error: Class info cache not found."
+          exit 1
+        fi
+        cp ${{ github.workspace }}/docs/llvm/ylib_class_info.cpp .
         cmake .. -G "Unix Makefiles" \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
                  -DANDROID_ABI=${{ matrix.cmake_arch }} \
                  -DANDROID_PLATFORM=android-21 \
-                 -DBUILD_YLIB_ARCH=${{ matrix.cmake_arch }} \
-                 -DCMAKE_PREFIX_PATH=${{ github.workspace }}/third_part/build/install
+                 -DBUILD_YLIB_ARCH=${{ matrix.build_ylib_arch }} \
+                 -DCMAKE_PREFIX_PATH=${{ github.workspace }}/build_android_${{ matrix.build_ylib_arch }}/install
         make -j$(nproc)
diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -7,7 +7,12 @@ on:
     branches: [ "master" ]
 
 jobs:
+  generate-info:
+    name: Generate Class Info
+    uses: ./.github/workflows/class_info.yml
+
   build:
+    needs: generate-info
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.runner }}
     strategy:
@@ -19,9 +24,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: ""
-            toolchain_file: ""
-            build_dir: "build_x64_gcc"
-            cmake_params: ""
+            toolchain_file: "toolchains/linux_x64_gcc.cmake"
+            build_dir: "build_linux_x64"
             build_deps_arch: "x64"
 
           - name: "x64-clang"
@@ -29,9 +33,8 @@ jobs:
             compiler: "clang"
             runner: "ubuntu-latest"
             apt_packages: "clang"
-            toolchain_file: ""
-            build_dir: "build_x64_clang"
-            cmake_params: ""
+            toolchain_file: "toolchains/linux_x64_clang.cmake"
+            build_dir: "build_linux_x64_clang"
             build_deps_arch: "x64"
 
           - name: "x86-gcc"
@@ -39,9 +42,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "gcc-multilib g++-multilib"
-            toolchain_file: "../toolchains/linux_x64_gcc_m32.cmake"
-            build_dir: "build"
-            cmake_params: "-DBUILD_YLIB_ARCH=x86"
+            toolchain_file: "toolchains/linux_x64_gcc_m32.cmake"
+            build_dir: "build_linux_x86"
             build_deps_arch: "x86"
 
           - name: "x86-clang"
@@ -49,9 +51,8 @@ jobs:
             compiler: "clang"
             runner: "ubuntu-latest"
             apt_packages: "clang gcc-multilib g++-multilib"
-            toolchain_file: "../toolchains/linux_x64_clang_m32.cmake"
-            build_dir: "build"
-            cmake_params: "-DBUILD_YLIB_ARCH=x86"
+            toolchain_file: "toolchains/linux_x64_clang_m32.cmake"
+            build_dir: "build_linux_x86_clang"
             build_deps_arch: "x86"
 
           - name: "aarch64-gcc"
@@ -59,9 +60,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "g++-aarch64-linux-gnu"
-            toolchain_file: "../toolchains/linux_aarch64_gcc.cmake"
-            build_dir: "build"
-            cmake_params: "-DBUILD_YLIB_ARCH=aarch64"
+            toolchain_file: "toolchains/linux_aarch64_gcc.cmake"
+            build_dir: "build_linux_aarch64"
             build_deps_arch: "aarch64"
 
           - name: "arm-gnueabi-gcc"
@@ -69,9 +69,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "g++-arm-linux-gnueabi"
-            toolchain_file: "../toolchains/linux_armgnueabi_gcc.cmake"
-            build_dir: "build"
-            cmake_params: "-DBUILD_YLIB_ARCH=armeabi"
+            toolchain_file: "toolchains/linux_armgnueabi_gcc.cmake"
+            build_dir: "build_linux_armeabi"
             build_deps_arch: "armeabi"
 
           - name: "arm-gnueabihf-gcc"
@@ -79,9 +78,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "g++-arm-linux-gnueabihf"
-            toolchain_file: "../toolchains/linux_armgnueabihf_gcc.cmake"
-            build_dir: "build"
-            cmake_params: "-DBUILD_YLIB_ARCH=armeabihf"
+            toolchain_file: "toolchains/linux_armgnueabihf_gcc.cmake"
+            build_dir: "build_linux_armeabihf"
             build_deps_arch: "armeabihf"
 
     steps:
@@ -94,12 +92,12 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y ${{ matrix.apt_packages }}
         fi
-        if [ "${{ matrix.compiler }}" = "clang" ]; then
-          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
-          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
-        fi
-        chmod +x build_deps.sh
+        # if [ "${{ matrix.compiler }}" = "clang" ]; then
+        #   sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
+        #   sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
+        # fi
         mkdir -p ${{ matrix.build_dir }}
+        mkdir -p $GITHUB_WORKSPACE/qemu-install/
 
     - name: Cache and Setup QEMU
       if: startsWith(matrix.arch, 'arm') || matrix.arch == 'aarch64'
@@ -116,11 +114,11 @@ jobs:
         if [ "${{ matrix.arch }}" != "aarch64" ]; then
           QEMU_TARGET="arm-linux-user"
         fi
-        sudo apt-get install -y ninja-build
+        sudo apt-get install -y ninja-build libglib2.0-dev
         git clone --depth 1 --branch v5.2.0 https://github.com/qemu/qemu.git
         cd qemu
         mkdir build && cd build
-        ../configure --prefix=$(pwd)/install --target-list=${QEMU_TARGET} --disable-system
+        ../configure --prefix=$(pwd)/install --target-list=${QEMU_TARGET} --disable-system --disable-werror
         make -j$(nproc)
         make install
         cp -r install/* $GITHUB_WORKSPACE/qemu-install/
@@ -128,20 +126,35 @@ jobs:
     - name: Build Third-Party Dependencies (CMake)
       working-directory: third_part
       run: |
-        mkdir build && cd build
-        cmake .. -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_part/build/install \
-                 ${{ matrix.toolchain_file != '' && format('-DCMAKE_TOOLCHAIN_FILE={0}/{1}', github.workspace, matrix.toolchain_file) || '' }}
+        mkdir build_linux_${{ matrix.build_deps_arch }} && cd build_linux_${{ matrix.build_deps_arch }}
+        cmake .. -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_part/build_linux_${{ matrix.build_deps_arch }}/install \
+                 -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/${{matrix.toolchain_file}} \
+                 -DBUILD_YLIB_ARCH=${{matrix.build_deps_arch}}
         cmake --build .
+
+    - name: Cache Class Info
+      uses: actions/cache@v4
+      id: restore-cache
+      with:
+        path: docs/llvm/ylib_class_info.cpp
+        key: ylib-class-info-${{ github.sha }}
+        restore-keys: |
+          ylib-class-info-
 
     - name: Build yLib
       working-directory: ${{ matrix.build_dir }}
       run: |
+        if [ "${{ steps.restore-cache.outputs.cache-hit }}" != "true" ]; then
+          echo "Error: Class info cache not found. The 'generate-info' job might have failed."
+          exit 1
+        fi
+        cp $GITHUB_WORKSPACE/docs/llvm/ylib_class_info.cpp $GITHUB_WORKSPACE/${{ matrix.build_dir }}
         cmake .. -G "Unix Makefiles" \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
                  -DCMAKE_PREFIX_PATH=${{ github.workspace }}/third_part/build/install \
-                 ${{ matrix.toolchain_file != '' && format('-DCMAKE_TOOLCHAIN_FILE={0}', matrix.toolchain_file) || '' }} \
-                 ${{ matrix.cmake_params }}
+                 -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/${{matrix.toolchain_file}} \
+                 -DBUILD_YLIB_ARCH=${{matrix.build_deps_arch}}
         make -j$(nproc)
         make install
 
@@ -149,8 +162,10 @@ jobs:
       working-directory: ${{ matrix.build_dir }}
       run: |
         if [ "${{ matrix.arch }}" = "x64" ] || [ "${{ matrix.arch }}" = "x86" ]; then
-          ./bin/yLibTests
-        else
+          cd install/tests
+          ./scripts_for_tests.sh
+        elif [ "${{ matrix.arch }}" = "aarch64" ]
+        then
           export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
           cd install/tests
           QEMU_BIN="qemu-${{ matrix.arch }}"
@@ -162,27 +177,6 @@ jobs:
             QEMU_BIN="qemu-arm"
           fi
           ./scripts_for_tests.sh ${QEMU_BIN}
+        else
+          echo "This arch(${{ matrix.arch }}) don't support test."
         fi
-
-  code-coverage:
-    name: Code Coverage
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout yLib
-        uses: actions/checkout@v4
-
-      - name: Setup Environment
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y lcov
-
-      - name: Build for Code Coverage
-        run: |
-          chmod +x generate_code_coverage_infos.sh
-          ./generate_code_coverage_infos.sh rebuild
-
-      - name: Upload Coverage Report
-        uses: actions/upload-artifact@v3
-        with:
-          name: code-coverage-report
-          path: build_codecoverage/cover_report/
