fix ci

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,12 +1,18 @@
 name: Android Build Matrix
 
-on:  push:
+on:
+  push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
 
 jobs:
+  generate-info:
+    name: Generate Class Info
+    uses: ./.github/workflows/class_info.yml
+
   build:
+    needs: generate-info
     name: ${{ matrix.name }}
     runs-on: ubuntu-latest
     strategy:
@@ -41,16 +47,30 @@ jobs:
     - name: Build Third-Party Dependencies (CMake)
       working-directory: third_part
       run: |
-        mkdir build && cd build
+        mkdir build_android_${{ matrix.build_dir_suffix }} && cd build_android_${{ matrix.build_dir_suffix }}
         cmake .. -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_part/build/install \
                  -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
                  -DANDROID_ABI=${{ matrix.cmake_arch }} \
                  -DANDROID_PLATFORM=android-21
         cmake --build .
 
+    - name: Cache Class Info
+      id: cache-class-info
+      uses: actions/cache@v4
+      with:
+        path: docs/llvm/ylib_class_info.cpp
+        key: ylib-class-info-${{ github.sha }}
+        restore-keys: |
+          ylib-class-info-
+
     - name: Build yLib
       working-directory: build_android_${{ matrix.build_dir_suffix }}
       run: |
+        if [ "${{ steps.cache-class-info.outputs.cache-hit }}" != "true" ]; then
+          echo "Error: Class info cache not found."
+          exit 1
+        fi
+        cp ${{ github.workspace }}/docs/llvm/ylib_class_info.cpp .
         cmake .. -G "Unix Makefiles" \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -7,7 +7,12 @@ on:
     branches: [ "master" ]
 
 jobs:
+  generate-info:
+    name: Generate Class Info
+    uses: ./.github/workflows/class_info.yml
+
   build:
+    needs: generate-info
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.runner }}
     strategy:
@@ -19,8 +24,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: ""
-            toolchain_file: "/toolchains/linux_x64_gcc.cmake"
-            build_dir: "build_x64_gcc"
+            toolchain_file: "toolchains/linux_x64_gcc.cmake"
+            build_dir: "build_linux_x64"
             cmake_params: "-DBUILD_YLIB_ARCH=x86_64"
             build_deps_arch: "x64"
 
@@ -29,8 +34,8 @@ jobs:
             compiler: "clang"
             runner: "ubuntu-latest"
             apt_packages: "clang"
-            toolchain_file: "/toolchains/linux_x64_clang.cmake"
-            build_dir: "build_x64_clang"
+            toolchain_file: "toolchains/linux_x64_clang.cmake"
+            build_dir: "build_linux_x64_clang"
             cmake_params: "-DBUILD_YLIB_ARCH=x86_64"
             build_deps_arch: "x64"
 
@@ -39,8 +44,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "gcc-multilib g++-multilib"
-            toolchain_file: "/toolchains/linux_x64_gcc_m32.cmake"
-            build_dir: "build"
+            toolchain_file: "toolchains/linux_x64_gcc_m32.cmake"
+            build_dir: "build_linux_x86"
             cmake_params: "-DBUILD_YLIB_ARCH=x86"
             build_deps_arch: "x86"
 
@@ -49,8 +54,8 @@ jobs:
             compiler: "clang"
             runner: "ubuntu-latest"
             apt_packages: "clang gcc-multilib g++-multilib"
-            toolchain_file: "/toolchains/linux_x64_clang_m32.cmake"
-            build_dir: "build"
+            toolchain_file: "toolchains/linux_x64_clang_m32.cmake"
+            build_dir: "build_linux_x86_clang"
             cmake_params: "-DBUILD_YLIB_ARCH=x86"
             build_deps_arch: "x86"
 
@@ -59,8 +64,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "g++-aarch64-linux-gnu"
-            toolchain_file: "/toolchains/linux_aarch64_gcc.cmake"
-            build_dir: "build"
+            toolchain_file: "toolchains/linux_aarch64_gcc.cmake"
+            build_dir: "build_linux_aarch64"
             cmake_params: "-DBUILD_YLIB_ARCH=aarch64"
             build_deps_arch: "aarch64"
 
@@ -69,8 +74,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "g++-arm-linux-gnueabi"
-            toolchain_file: "/toolchains/linux_armgnueabi_gcc.cmake"
-            build_dir: "build"
+            toolchain_file: "toolchains/linux_armgnueabi_gcc.cmake"
+            build_dir: "build_linux_armeabi"
             cmake_params: "-DBUILD_YLIB_ARCH=armeabi"
             build_deps_arch: "armeabi"
 
@@ -79,8 +84,8 @@ jobs:
             compiler: "gcc"
             runner: "ubuntu-latest"
             apt_packages: "g++-arm-linux-gnueabihf"
-            toolchain_file: "/toolchains/linux_armgnueabihf_gcc.cmake"
-            build_dir: "build"
+            toolchain_file: "toolchains/linux_armgnueabihf_gcc.cmake"
+            build_dir: "build_linux_armeabihf"
             cmake_params: "-DBUILD_YLIB_ARCH=armeabihf"
             build_deps_arch: "armeabihf"
 
@@ -127,15 +132,29 @@ jobs:
     - name: Build Third-Party Dependencies (CMake)
       working-directory: third_part
       run: |
-        mkdir build && cd build
-        cmake .. -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_part/build/install \
+        mkdir build_linux_${{ build_deps_arch }} && cd build_linux_${{ build_deps_arch }}
+        cmake .. -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_part/build_linux_${{ build_deps_arch }}/install \
                  -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/${{matrix.toolchain_file}} \
                  ${{ matrix.cmake_params }}
         cmake --build .
 
+    - name: Cache Class Info
+      uses: actions/cache@v4
+      id: restore-cache
+      with:
+        path: docs/llvm/ylib_class_info.cpp
+        key: ylib-class-info-${{ github.sha }}
+        restore-keys: |
+          ylib-class-info-
+
     - name: Build yLib
       working-directory: ${{ matrix.build_dir }}
       run: |
+        if [ "${{ steps.restore-cache.outputs.cache-hit }}" != "true" ]; then
+          echo "Error: Class info cache not found. The 'generate-info' job might have failed."
+          exit 1
+        fi
+        cp $GITHUB_WORKSPACE/docs/llvm/ylib_class_info.cpp $GITHUB_WORKSPACE/${{ matrix.build_dir }}
         cmake .. -G "Unix Makefiles" \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
@@ -163,26 +182,3 @@ jobs:
           fi
           ./scripts_for_tests.sh ${QEMU_BIN}
         fi
-
-  code-coverage:
-    name: Code Coverage
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout yLib
-        uses: actions/checkout@v4
-
-      - name: Setup Environment
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y lcov
-
-      - name: Build for Code Coverage
-        run: |
-          chmod +x generate_code_coverage_infos.sh
-          ./generate_code_coverage_infos.sh rebuild
-
-      - name: Upload Coverage Report
-        uses: actions/upload-artifact@v3
-        with:
-          name: code-coverage-report
-          path: build_codecoverage/cover_report/
diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -7,7 +7,12 @@ on:
     branches: [ "master" ]
 
 jobs:
+  generate-info:
+    name: Generate Class Info
+    uses: ./.github/workflows/class_info.yml
+
   build:
+    needs: generate-info
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.runner }}
     strategy:
@@ -15,76 +20,118 @@ jobs:
       matrix:
         include:
           - name: "x64-vs2022"
-            vs_version: "2022"
             generator: "Visual Studio 17 2022"
             arch: "x64"
             cmake_arch: "x64"
-            runner: "windows-2022"
+            runner: "windows-latest"
+            build_dir: "build_vs2022_x64"
           - name: "x86-vs2022"
-            vs_version: "2022"
             generator: "Visual Studio 17 2022"
             arch: "x86"
             cmake_arch: "Win32"
-            runner: "windows-2022"
+            runner: "windows-latest"
+            build_dir: "build_vs2022_x86"
           - name: "x64-vs2019"
-            vs_version: "2019"
             generator: "Visual Studio 16 2019"
             arch: "x64"
             cmake_arch: "x64"
             runner: "windows-2019"
+            build_dir: "build_vs2019_x64"
           - name: "x86-vs2019"
-            vs_version: "2019"
             generator: "Visual Studio 16 2019"
             arch: "x86"
             cmake_arch: "Win32"
             runner: "windows-2019"
-          - name: "x64-vs2017"
-            vs_version: "2017"
-            generator: "Visual Studio 15 2017"
-            arch: "x64"
-            cmake_arch: "x64"
-            runner: "windows-2019"
-          - name: "x86-vs2017"
-            vs_version: "2017"
-            generator: "Visual Studio 15 2017"
-            arch: "x86"
-            cmake_arch: "Win32"
-            runner: "windows-2019"
-          - name: "x64-vs2015"
-            vs_version: "2015"
-            generator: "Visual Studio 14 2015"
-            arch: "x64"
-            cmake_arch: "x64"
-            runner: "windows-2019"
-          - name: "x86-vs2015"
-            vs_version: "2015"
-            generator: "Visual Studio 14 2015"
-            arch: "x86"
-            cmake_arch: "Win32"
-            runner: "windows-2019"
+            build_dir: "build_vs2019_x86"
 
     steps:
     - name: Checkout yLib
       uses: actions/checkout@v4
 
+    - name: Setup Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.x'
+
+    - name: Setup MSVC
+      uses: microsoft/setup-msvc-dev@v1
+      with:
+        architecture: ${{ matrix.arch }}
+
     - name: Build Third-Party Dependencies (CMake)
       shell: cmd
       run: |
-        mkdir third_part\build
-        cd third_part\build
-        cmake .. -G "${{ matrix.generator }}" -A ${{ matrix.cmake_arch }} -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\third_part\build\install" -Dcompile_tool_set=v${{ matrix.vs_version }} -Dcompile_tool_arch=${{ matrix.cmake_arch }}
+        cd third_part
+        mkdir build_${{ matrix.build_dir }} && cd build_${{ matrix.build_dir }}
+        cmake .. -G "${{ matrix.generator }}" -A ${{ matrix.cmake_arch }} -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\third_part\build\install"
         cmake --build . --config Release
+
+    - name: Cache Class Info
+      id: restore-cache
+      uses: actions/cache@v4
+      with:
+        path: docs/llvm/ylib_class_info.cpp
+        key: ylib-class-info-${{ github.sha }}
+        restore-keys: |
+          ylib-class-info-
+
+    # - name: Install LLVM and Build class_ana
+    #   if: steps.cache-ylib-class_ana.outputs.cache-hit != 'true'
+    #   shell: pwsh
+    #   run: |
+    #     $LLVM_VERSION = "18.1.8"
+    #     $LLVM_URL = "https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-pc-windows-msvc.tar.xz"
+    #     $LLVM_ARCHIVE = "llvm.tar.xz"
+    #     $LLVM_DIR = "clang+llvm-$LLVM_VERSION-x86_64-pc-windows-msvc"
+
+    #     echo "Downloading LLVM from $LLVM_URL"
+    #     Invoke-WebRequest -Uri $LLVM_URL -OutFile $LLVM_ARCHIVE
+
+    #     echo "Extracting LLVM..."
+    #     tar -xf $LLVM_ARCHIVE
+
+    #     $env:LLVM_PATH = Join-Path $env:GITHUB_WORKSPACE $LLVM_DIR
+    #     $env:LLVM_INCLUDE_PATH = Join-Path $env:LLVM_PATH "include"
+    #     $env:LLVM_LIB_PATH = Join-Path $env:LLVM_PATH "lib"
+
+    #     echo "Merging LLVM and Clang static libraries..."
+    #     python docs/llvm/mege_llvm_lib.py $env:LLVM_LIB_PATH
+
+    #     cd docs/llvm
+
+    #     echo "Compiling class_ana.cpp..."
+    #     cl.exe class_ana.cpp /I "$env:LLVM_INCLUDE_PATH" /std:c++17 /MD /EHsc /Fe:class_ana.exe /link /LIBPATH:"$env:LLVM_LIB_PATH" clang.lib LLVM.lib
+
+    # - name: Generate Class Info
+    #   shell: pwsh
+    #   run: |
+    #     mkdir ${{ github.workspace }}\${{ matrix.build_dir }}
+    #     cd docs/llvm
+    #     python class_ana.py --ylib_root=$env:GITHUB_WORKSPACE --output=${{ github.workspace }}\${{ matrix.build_dir }}
 
     - name: Build yLib
       shell: cmd
       run: |
-        mkdir build_${{ matrix.arch }}_vs${{ matrix.vs_version }}
-        cd build_${{ matrix.arch }}_vs${{ matrix.vs_version }}
-        cmake .. -G "${{ matrix.generator }}" -A ${{ matrix.cmake_arch }} -DCMAKE_PREFIX_PATH="${{ github.workspace }}\third_part\build\install"
-        cmake --build . --config Release
+        if ("${{ steps.restore-cache.outputs.cache-hit }}" -ne "true") {
+          Write-Error "Class info cache not found. The 'generate-info' job might have failed."
+          exit 1
+        }
+        cp ${{ github.workspace }}\docs\llvm\ylib_class_info.cpp ${{ github.workspace }}\${{ matrix.build_dir }}
+        cd ${{ matrix.build_dir }}
+        cmake .. -G "${{ matrix.generator }}" -A ${{ matrix.cmake_arch }} `
+                 -DCMAKE_INSTALL_PREFIX=install `
+                 -DCMAKE_PREFIX_PATH="${{ github.workspace }}\third_part\build\install"
+        cmake --build . --config Release --target install
 
     - name: Execute Tests
       shell: cmd
       run: |
-        cd build_${{ matrix.arch }}_vs${{ matrix.vs_version }}\bin\Release
-        yLibTests.exe
+        cd ${{ matrix.build_dir }}\install\tests
+        scripts_for_tests.bat
+
+    - name: Package Artifacts
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: ylib-windows-${{ matrix.name }}
+        path: ${{ matrix.build_dir }}/install/
